/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TempleRouteImport } from './routes/temple'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HabitsIdRouteImport } from './routes/habits.$id'

const TempleRoute = TempleRouteImport.update({
  id: '/temple',
  path: '/temple',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIdRoute = HabitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HabitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habits': typeof HabitsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/temple': typeof TempleRoute
  '/habits/$id': typeof HabitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habits': typeof HabitsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/temple': typeof TempleRoute
  '/habits/$id': typeof HabitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/habits': typeof HabitsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/temple': typeof TempleRoute
  '/habits/$id': typeof HabitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/habits' | '/profile' | '/temple' | '/habits/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/habits' | '/profile' | '/temple' | '/habits/$id'
  id: '__root__' | '/' | '/habits' | '/profile' | '/temple' | '/habits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabitsRoute: typeof HabitsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  TempleRoute: typeof TempleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temple': {
      id: '/temple'
      path: '/temple'
      fullPath: '/temple'
      preLoaderRoute: typeof TempleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$id': {
      id: '/habits/$id'
      path: '/$id'
      fullPath: '/habits/$id'
      preLoaderRoute: typeof HabitsIdRouteImport
      parentRoute: typeof HabitsRoute
    }
  }
}

interface HabitsRouteChildren {
  HabitsIdRoute: typeof HabitsIdRoute
}

const HabitsRouteChildren: HabitsRouteChildren = {
  HabitsIdRoute: HabitsIdRoute,
}

const HabitsRouteWithChildren =
  HabitsRoute._addFileChildren(HabitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabitsRoute: HabitsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  TempleRoute: TempleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
